on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release & Generate executables

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

  create_dist:
    name: Create dist directory
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create directory
        run: mkdir ./dist

  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.28
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: linux
          goarch: amd64
          md5sum: false
          binary_name: norsys-project-base-generator-linux-amd64
          retry: 3
  release-linux-gui-amd64:
    name: release linux/amd64 gui app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.28
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: linux
          goarch: amd64
          md5sum: false
          binary_name: norsys-project-base-generator-gui-linux-amd64
          project_path: ./gui
          retry: 3
  release-windows-amd64:
    name: release windows/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.28
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: windows
          goarch: amd64
          md5sum: false
          binary_name: norsys-project-base-generator-windows-amd64
          retry: 3
  release-windows-gui-amd64:
    name: release windows/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.28
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: windows
          goarch: amd64
          md5sum: false
          binary_name: norsys-project-base-generator-gui-windows-amd64
          project_path: ./gui
          retry: 3
  release-darwin-amd64:
    name: release darwin/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.28
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: darwin
          goarch: amd64
          md5sum: false
          binary_name: norsys-project-base-generator-darwin-amd64
          retry: 3
  release-darwin-gui-amd64:
    name: release darwin/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.28
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: darwin
          goarch: amd64
          md5sum: false
          binary_name: norsys-project-base-generator-gui-darwin-amd64
          project_path: ./gui
          retry: 3
  release-darwin-arm64:
    name: release darwin/arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.28
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: darwin
          goarch: arm64
          md5sum: false
          binary_name: norsys-project-base-generator-darwin-arm64
          retry: 3
  release-darwin-gui-arm64:
    name: release darwin/arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.28
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: darwin
          goarch: arm64
          md5sum: false
          binary_name: norsys-project-base-generator-gui-darwin-arm64
          project_path: ./gui
          retry: 3
