on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

  create_dist:
    name: Create dist directory
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create directory
        run: mkdir ./dist

  release-linux-amd64-cli:
    name: release linux/amd64 - cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.28
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: linux
          goarch: amd64
          project_path: ./cli
          md5sum: false
          binary_name: norsys-project-base-generator-linux-amd64-cli
  release-windows-amd64-cli:
    name: release windows/amd64 - cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.28
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: windows
          goarch: amd64
          project_path: ./cli
          md5sum: false
          binary_name: norsys-project-base-generator-windows-amd64-cli
  release-darwin-amd64-cli:
    name: release darwin/amd64 - cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.28
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: darwin
          goarch: amd64
          project_path: ./cli
          md5sum: false
          binary_name: norsys-project-base-generator-darwin-amd64-cli
  release-darwin-arm64-cli:
    name: release darwin/arm64 - cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.28
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: darwin
          goarch: arm64
          project_path: ./cli
          md5sum: false
          binary_name: norsys-project-base-generator-darwin-arm64-cli

  release-linux-amd64-gui:
    name: release linux/amd64 - gui
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.28
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: linux
          goarch: amd64
          project_path: ./gui
          md5sum: false
          binary_name: norsys-project-base-generator-linux-amd64-gui
          pre_command: |
            apt-get update -y &&
            apt-get install libx11-dev xorg-dev -y &&
            apt-get install cmake pkg-config -y &&
            apt-get install mesa-utils libglu1-mesa-dev freeglut3-dev mesa-common-dev -y &&
            apt-get install libglew-dev libglfw3-dev libglm-dev -y &&
            apt-get install libao-dev libmpg123-dev -y
  release-windows-amd64-gui:
    name: release windows/amd64 - gui
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.28
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: windows
          goarch: amd64
          project_path: ./gui
          md5sum: false
          binary_name: norsys-project-base-generator-windows-amd64-gui
          pre_command: |
            apt-get update -y &&
            apt-get install libx11-dev xorg-dev -y &&
            apt-get install cmake pkg-config -y &&
            apt-get install mesa-utils libglu1-mesa-dev freeglut3-dev mesa-common-dev -y &&
            apt-get install libglew-dev libglfw3-dev libglm-dev -y &&
            apt-get install libao-dev libmpg123-dev -y
  release-darwin-amd64-gui:
    name: release darwin/amd64 - gui
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.28
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: darwin
          goarch: amd64
          project_path: ./gui
          md5sum: false
          binary_name: norsys-project-base-generator-darwin-amd64-gui
  release-darwin-arm64-gui:
    name: release darwin/arm64 - gui
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.28
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: darwin
          goarch: arm64
          project_path: ./gui
          md5sum: false
          binary_name: norsys-project-base-generator-darwin-arm64-gui